version: '3.7'

services:

  wordpress:
    image: wordpress:${VERSION_WORDPRESS}-php${VERSION_PHP}-apache
    restart: always
    volumes:
      - ./data/wp-content/:/var/www/html/wp-content/
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_CONFIG_EXTRA: define('WP_HOME','http://localhost:8080'); define('WP_SITEURL','http://localhost:8080');
    depends_on:
      - db

  db:
    image: mariadb:${VERSION_MARIADB}
    restart: always
    volumes:
      - ./data/db-backup/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
