version: '3.7'

services:

  wordpress:
    image: wordpress-local
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
      WORDPRESS_TABLE_PREFIX: ftvv_
      # WORDPRESS_TABLE_PREFIX: jqru_
    depends_on:
      - db

  db:
    image: mariadb-local
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
